services:
  - type: web
    name: logistica-camiones
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --log-file -"
    healthCheckPath: "/login"
    autoDeploy: true
    envVars:
      - key: DB_HOST
        fromEnvVar: DB_HOST
      - key: DB_NAME
        fromEnvVar: DB_NAME
      - key: DB_USER
        fromEnvVar: DB_USER
      - key: DB_PASSWORD
        fromEnvVar: DB_PASSWORD
      - key: DB_PORT
        fromEnvVar: DB_PORT
      - key: FLASK_ENV
        value: production
      - key: ADMIN_USERNAME
        fromEnvVar: ADMIN_USERNAME
      - key: ADMIN_PASSWORD
        fromEnvVar: ADMIN_PASSWORD
 
